/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_VDAC_REF_GATT                  27
#define gattdb_IADC_REF_GATT                  29
#define gattdb_VOLTAGE_START                  31
#define gattdb_VOLTAGE_STOP                   33
#define gattdb_VOLTAGE_STEP                   35
#define gattdb_PULSE_HEIGHT                   37
#define gattdb_PULSE_WIDTH                    39
#define gattdb_TIME_BEFORE_TRIAL              45
#define gattdb_TIME_AFTER_TRIAL               47
#define gattdb_SAMPLES_PER_PULSE              49
#define gattdb_RUN_EXPERIMENT                 51
#define gattdb_ADC_RESULT                     54
#define gattdb_GAIN_CHANNEL                   57
#define gattdb_ELECTRODE_CHANNEL              59
#define gattdb_OPERATING_MODE                 61
#define gattdb_LINEAR_SWEEP_RATE              63
#define gattdb_LINEAR_SWEEP_SAMPLE_RATE       65
#define gattdb_TIME_BEFORE_PULSE              67
#define gattdb_TIME_AFTER_PULSE               69

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                21
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   11
#define gattdb_model_number_string_len        10
#define gattdb_hardware_revision_string_len   5
#define gattdb_firmware_revision_string_len   8
#define gattdb_system_id_len                  8
#define gattdb_VDAC_REF_GATT_len              2
#define gattdb_IADC_REF_GATT_len              2
#define gattdb_VOLTAGE_START_len              2
#define gattdb_VOLTAGE_STOP_len               2
#define gattdb_VOLTAGE_STEP_len               2
#define gattdb_PULSE_HEIGHT_len               2
#define gattdb_PULSE_WIDTH_len                2
#define gattdb_TIME_BEFORE_TRIAL_len          2
#define gattdb_TIME_AFTER_TRIAL_len           2
#define gattdb_SAMPLES_PER_PULSE_len          2
#define gattdb_RUN_EXPERIMENT_len             1
#define gattdb_ADC_RESULT_len                 8
#define gattdb_GAIN_CHANNEL_len               1
#define gattdb_ELECTRODE_CHANNEL_len          1
#define gattdb_OPERATING_MODE_len             1
#define gattdb_LINEAR_SWEEP_RATE_len          2
#define gattdb_LINEAR_SWEEP_SAMPLE_RATE_len   2
#define gattdb_TIME_BEFORE_PULSE_len          1
#define gattdb_TIME_AFTER_PULSE_len           1


#endif // __GATT_DB_H
